# Generated by Django 5.1.7 on 2025-04-04 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created'], 'verbose_name': 'Answer'},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created'], name='home_answer_created_87afa9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created'], name='home_questi_created_44ee66_idx'),
        ),
    ]
